version: 0.2 
phases: 
  install: 
    runtime-versions: 
        nodejs: 10 
  build: 
    commands: 
      - npm install time 
      - aws cloudformation package --template-file template.yaml --s3-bucket bukat --output-template-file outputtemplate.yaml 
artifacts: 
  type: zip 
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
