version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10 
  build:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket babu-10 --output-template-file outputSamTemplate.yaml
  post-build:
    type: zip
    files:
      - samTemplate.yaml
      - outputSamTemplate.yaml
